function UnInstallECGkit()

    %path related constants.
    root_path = [fileparts(mfilename('fullpath')) filesep ];

    fprintf(1, [ ... 
            '+---------------------------------+\n' ...
            '|        Mariano''s ECGkit         |\n' ...
            '+---------------------------------+\n' ...
            ]);
        
    fprintf(1, 'Removing paths. ' );
    
    %path related constants.
    default_paths = { ...
                        [root_path ';' ]; ...
                        [root_path 'common' filesep ';' ]; ...
                        [ root_path 'common' filesep 'wavedet' filesep ';' ]; ...
                        [ root_path 'common' filesep 'prtools' filesep ';' ]; ...
                        [ root_path 'common' filesep 'prtools_addins' filesep ';' ]; ...
                        [ root_path 'common' filesep 'kur' filesep ';' ]; ...
                        [ root_path 'common' filesep 'LIBRA' filesep ';' ]; ...
                        [root_path 'a2hbc' filesep ';' ]; ...
                        [root_path 'a2hbc' filesep 'scripts' filesep ';' ]; ...
                    };

    default_paths = char(default_paths)';
    default_paths = (default_paths(:))';
    rmpath(default_paths);

    savepath
    
    fprintf(1, 'done !\n' );

    fprintf(1, 'Thanks for trying the kit.\n\nNow you can safely delete %s.\n', root_path );
    
end
