%% (Internal) Wave definitions for ECG delineators used in the toolbox
%   
%   Fields used in the payload variables generated by ECGtask_ECG_delineation
% 
% 
% See also ECGtask_ECG_delineation
% 
% Author: Mariano Llamedo Soria llamedom@electron.frba.utn.edu.ar
% Version: 0.1 beta
% Last update: 09/05/2016
% Birthdate  : 09/05/2016
% Copyright 2008-2016
% 
cAnnotationOutputFields = { 'Pon' 'P' 'Poff' 'Ptipo' 'QRSon' 'qrs' 'Q' 'R' 'S' 'QRSoff' 'Ton' 'T' 'Tprima' 'Toff' 'Ttipo' };
cAnnotationSLRfields =    { 'Pon' 'P' 'Poff'         'QRSon' 'qrs'             'QRSoff' 'Ton' 'T' 'Tprima' 'Toff' };

cHL7aECG_translation = ...    
    { 'MDC_ECG_WAVC_PWAVE',   'P', 'Pon', 'Poff';
      'MDC_ECG_WAVC_QWAVE',   'Q', '', '';
      'MDC_ECG_WAVC_RWAVE',   'R', '', '';
      'MDC_ECG_WAVC_SWAVE',   'S', '', '';
      'MDC_ECG_WAVC_QRSWAVE', 'qrs', 'QRSon', 'QRSoff';
      'MDC_ECG_WAVC_QSWAVE',  'qrs', 'QRSon', 'QRSoff';
      'MDC_ECG_WAVC_TWAVE',   'T', 'Ton', 'Toff' };
